site_name: Fibroblast Data Explorer - Immunobiology Lab St.Gallen
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: indigo
      accent: red
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: indigo
      accent: red
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
  favicon: images/favicon.png
  logo: images/favicon3.png
nav:
    - Home: index.md
    - Mouse: 
        - Lymph node B cell interacting reticular cells: mouse/LNBRC.md
        - Lymph node fibroblastic reticular cells - LCMV and naive: mouse/LNFRC.md
        - Splenic white pulp fibroblastic reticular cells: mouse/SWPFRC.md
        - Peyer's patch fibroblastic reticular cells: mouse/PPFRC.md
        - Cross organ B cell interacting reticular cells: mouse/CrossSLO.md
    - Human:
        - Tonsilar stromal cells: human/Tonsil.md
        - B cell interacting reticular cells - Tonsils and lymph nodes: human/CrossSLO.md
    - Contact: contact.md
plugins:
  - search
use_directory_urls: false
markdown_extensions:
  - attr_list
extra_css:
  - stylesheets/extra.css